### PR TITLE
Add xcd currency

### PR DESCRIPTION
**Pull request by shankarGdev**
Add missing xcd currency to currency data

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, can you add it below `xaf`, so the IDs are in alphabetical order. Thanks!

**Comment by shankarGdev** [comment]
> Hey, can you add it below `xaf`, so the IDs are in alphabetical order. Thanks!

Will move it. Also planning to remaining missing currencies too and will follow that order.

**Comment by danharrin** [comment]
Thanks, let me know when you're ready for me to review 👍

**Comment by shankarGdev** [comment]
Hey, you can merge this, will do remaining is separate pull request,

**Pull request merged**
