### PR TITLE
Add time offset on timezones-en

### PR DESCRIPTION
**Pull request by imsus**
This will help devs to add more context to their label.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, the tests are all failing for this. Can you investigate why please?

**Comment by imsus** [comment]
> Hey, the tests are all failing for this. Can you investigate why please?

Sorry, I forgot to add quotes.

**Comment by danharrin** [comment]
Please also add this new column to do the docs :)

**Comment by danharrin** [comment]
How do we handle timezones which use daylight saving? Because the offset isn't always correct

Maybe it's better to not store this in CSV...

**Comment by imsus** [comment]
Since there are many versions of offset because of daylight saving, how about rename the column to `time_offset_without_daylight_saving`? Kinda too long, but meaningful.

Since my use case is for creating select options timezone. Most of people won't bother looking at offset. Instead they use alphabet. https://www.nngroup.com/articles/time-zone-selectors/

Or maybe you can check how savvycal handle their [timezone api service](https://savvycal.com/time-zone-api/), especially [timezone list response](https://savvycal.com/docs/api/endpoints/time-zones#list-time-zones:~:text=%22offset%22%3A%20%2D18000%2C%0A%20%20%20%20%22offset_std%22%3A%203600%2C%0A%20%20%20%20%22offset_utc%22%3A%20%2D21600%2C).

**Comment by danharrin** [comment]
I think you should use PHP's `timezone_offset_get()` instead of storing this in SQL, otherwise the numbers are wrong half of the time. Thanks for the PR.

**Pull request closed without merging**
