### PR TITLE
Added support for akaunting/laravel-money 5.x

### PR DESCRIPTION
**Pull request by stephenjude**
- Added support for akaunting/laravel-money 5.x

### CODE REVIEW

**Comment by danharrin** [comment]
Is it worth adding v3 and v4 support too?

**Comment by stephenjude** [comment]
For v3, yes, but v4 and v5 both support Laravel 10.

But I have added all so we don't break anything.

**Comment by danharrin** [comment]
Thanks

**Comment by stephenjude** [comment]
The run-validation action is failing 😬

**Pull request merged**
