### PR TITLE
Translate Country Names

### PR DESCRIPTION
**Pull request by Jubeki**
Capital cities were not translated. I used https://github.com/unicode-cldr/cldr-localenames-full for the translations.
#1

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks for your work here! ❤️

For v1, I will be restructuring the whole project, so from there, we can work on restructuring this PR to match.

**Comment by Jubeki** [comment]
Okay just comment on this PR and I will update it accordingly. 👍

**Comment by Jubeki** [comment]
@danharrin I just saw that you probably tagged the wrong version 30 minutes ago:
Right now it is v1.2.0 instead of v0.2.0

You should probably tag the next big release as v2 instead of v1

**Comment by danharrin** [comment]
Hey! I've just released v2.0.0. This release brings major changes to the Squire ecosystem, including the split of models and their data sources into separate packages. As such, this PR will need updating to reflect this. If you're able to do this, that would be greatly appreciated! Feel free to open a new PR. I realise that this may take some time so don't worry if not :)

**Pull request closed without merging**
