### PR TITLE
Laravel 11 compatibility

### PR DESCRIPTION
**Pull request by orkhanahmadov**

### CODE REVIEW

**Comment by dwaynehertroys** [comment]
Can this be merged?

**Comment by danharrin** [comment]
I don't think it actually works, none of the package composer.json files have been touched

**Comment by orkhanahmadov** [comment]
@danharrin thanks. I did let me check. I didn't have this monorepo setup locally to run it

**Comment by orkhanahmadov** [comment]
@danharrin should be good now. Can you please give action runner another try?

**Comment by danharrin** [comment]
Actions are running

**Comment by danharrin** [comment]
Looks good now, thanks

**Pull request merged**
