### PR TITLE
Arabic translations & updates

### PR DESCRIPTION
**Pull request by onexer**
added arabic translations for:
* continents
* countries
* currencies

also updated following to match current status:
* root composer
* tests with successful results

### CODE REVIEW

**Comment by hsul4n** [comment]
@danharrin Looks like everything going well.

**Comment by danharrin** [comment]
Swamped with other work at the moment, I really do appreciate the contribution but since it's so large that it will take me a bit of time to review

**Comment by hsul4n** [comment]
Hey @danharrin, Any chance for merging Arabic translation. Everything looks fine.

**Comment by danharrin** [comment]
Thank you very much for the contribution, but I would like to refrain from adding any more translations to the existing models for now.

The way that the project is structured, you can release these packages yourself, and then PR a link to your package from my README.

This way, I am not maintaining too many translations that I do not use, and you have completed control and responsibility over the content. And your translation is discoverable by other users through our README.

Hope you understand my reasoning :)

**Pull request closed without merging**
