### PR TITLE
Add italy counties

### PR DESCRIPTION
**Pull request by clickanidea**
Added counties for Italy

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! Thanks for your work on this!

I was just in the middle of moving this data to a new `ItProvince` model - since "province" seemed most appropriate way to name this data at first look, and I assumed that you followed the pattern already laid out by `GbCounty`?

Anyway, I saw the [ISO 3166-2 documentation for Italy](https://en.wikipedia.org/wiki/ISO_3166-2:IT) and wondered if it's best to have provinces, consortia and cities handled all by the same model, or should they be separated into their own models?

I have a few of questions that will impact my decision on this, if you live in/know Italy then you may be able to answer:
- Do provinces, consortia and cities overlap at all?
- If they don't overlap, and you were filling out an address form for Italy, how would you specify which province/consortia/city you live in? Are all options usually on the same dropdown menu? Or are they separated?
- Is there a name that we can generalise provinces, consortia and cities with? Maybe "area"?

**Comment by danharrin** [comment]
Also, please remove the `.DS_Store` and `data/.DS_Store` files from the commit, doesn't look like I am able to for some reason.

**Comment by clickanidea** [comment]
> Hey! Thanks for your work on this!
> 
> I was just in the middle of moving this data to a new `ItProvince` model - since "province" seemed to be a more appropriate way to categorise this data when I first reviewed this PR.
> 
> Anyway, I saw the [ISO 3166-2 documentation for Italy](https://en.wikipedia.org/wiki/ISO_3166-2:IT) and wondered if it's best to have provinces, consortia and cities handled all by the same model, or should they be separated into their own models?
> 
> I have a few questions that will impact my decision on this, if you live in/know Italy then you may be able to answer:
> 
> * Do provinces, consortia and cities overlap at all?
> * If they don't overlap, and you were filling out an address form for Italy, how would you specify which province/consortia/city you live in? Are all options usually on the same dropdown menu? Or are they separated?
> * Is there a name that we can generalise provinces, consortia and cities with? Maybe "subregion"?
Consortia are not used at all and there is no overlap, there may be an overlap with province and city (Province of Milan and City of Milan), but  since there are around 9,000 cities in Italy in a typical form you fill the city manually and get the province from the dropdown.
Italy is divided in Regions, Provinces and Cities, but Regions are (99.99%) not requested in any communication. The only other data that would be useful (I guess not only in Italy) would be the zip code, but it can get difficult where in the same city you can have different zip codes for different Burroughs or the same city name in different regions. I made for myself a backend api with all cities, provinces and zip codes that I can  drill down in the form, but it would be outside the scope of a utility package I think.

**Comment by danharrin** [comment]
Hey! I've just released v2.0.0. This release brings major changes to the Squire ecosystem, including the split of models and their data sources into separate packages. As such, this PR will need updating to reflect this. If you're able to do this, that would be greatly appreciated! Feel free to open a new PR. I realise that this may take some time so don't worry if not :)

**Pull request closed without merging**
